version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
    - SHoogland
  versioning-strategy: increase

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
    - SHoogland

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
    - SHoogland