services:
  mongodb:
    image: mongo:8.0
    command: ["--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump

  tdorp-parse-server:
    image: ghcr.io/shoogland/timmerdorp-parse
    ports:
      - 1337:1337
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/dev
      - APP_ID=myAppId
      - JS_KEY=jsKey
      - REDIS_URI_CUSTOM=redis://valkey:6379/2
      - REDIS_URI_PARSE=redis://valkey:6379/5
      - ENVIRONMENT=development
      - PARSE_MOUNT=/1
      - PORT=1337
      - SERVER_URL=http://127.0.0.1:1337/1
      - MASTER_KEY=masterKey
      - REPLICA_SET=false
    depends_on:
      - mongodb
      - valkey

  valkey:
    image: "valkey/valkey:8.1.1-alpine"
    ports:
      - 6379:6379
