services:
  mongodb:
    image: mongo:7.0
    command: ["--bind_ip_all"]
    ports:
      - 27017:27017

  tdorp-parse-server:
    image: ghcr.io/shoogland/timmerdorp-parse
    ports:
      - 1337:1337
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/dev